import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  imageContainer: {
    flex: 1,
    width: "100%",
    height: "100%",
    overflow: "hidden",
    borderRadius: 12,
    backgroundColor: "rgba(15, 15, 15, 0.8)",
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  logoContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: 100,
    resizeMode: "contain",
    marginTop: 10,
  },
  imageLogo: {
    flex: 1,
    width: "55%",
    resizeMode: "contain",
  },
  carBrand: {
    color: "#888",
    fontWeight: "500",
    fontSize: 16,
    fontStyle: "italic",
    marginBottom: 4,
    textAlign: "center",
    width: "100%",
  },
  carName: {
    fontSize: 28,
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
    textTransform: "uppercase",
    paddingHorizontal: 10,
    textShadowColor: "rgba(1, 166, 179, 0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
    flexShrink: 1,
    width: "100%",
  },
  carDetailsContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    marginBottom: 5,
  },
  image: {
    width: "100%",
    height: 180,
    marginVertical: 10,
    resizeMode: "contain",
  },
  priceLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    width: "100%",
  },
  priceLabel: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 24,
    fontStyle: "italic",
    textShadowColor: "rgba(1, 166, 179, 0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
  },
  navButton: {
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#01a6b3",
    backgroundColor: "rgba(1, 166, 179, 0.2)",
    shadowColor: "#01a6b3",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 10,
  },
  navButtonText: {
    color: "#01a6b3",
    fontSize: 30,
    fontWeight: "bold",
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
  },
  loadingText: {
    color: "#fff",
    fontSize: 16,
    marginTop: 20,
    fontStyle: "italic",
  },
  navigationButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginVertical: 10,
    position: "relative",
    zIndex: 100,
    width: "100%",
  },
  navButtonBig: {
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
    borderWidth: 3,
    borderColor: "#01a6b3",
    backgroundColor: "rgba(1, 166, 179, 0.3)",
    shadowColor: "#01a6b3",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
    elevation: 10,
    zIndex: 100,
  },
  navButtonTextBig: {
    color: "#ffffff",
    fontSize: 36,
    fontWeight: "bold",
    marginTop: -4,
    textShadowColor: "#01a6b3",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
  },
});
